export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const TOGGLE_DARKTHEME = 'TOGGLE_DARKTHEME';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';